name: xfactor_wod
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  html: ^0.13.0
  http: ^0.11.0
  logs:
    git: https://github.com/pq/logs
  url_launcher: ^3.0.0

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
  - assets/logo_dark.png
  - assets/logo_light.png
